<?php
	// Establece el tamaño de los distitntos sets de valores que se utilizarán, siempre el set 0 será de valor 1 porque es para las respuestas abiertas
	$tamano_set_valores[0] = 1;
	$tamano_set_valores[1] = 2;
	$tamano_set_valores[2] = 10;
	// Establece el set de valores para las respuestas cerradas y las de opción múltiple
	$set_valores[1][0]['texto'] = "No aplica";
	$set_valores[1][0]['valor'] = 0;
	$set_valores[1][1]['texto'] = "Sí";
	$set_valores[1][1]['valor'] = 1;
	$set_valores[1][2]['texto'] = "No";
	$set_valores[1][2]['valor'] = -1;
	
	$set_valores[2][0]['texto'] = "No aplica";
	$set_valores[2][0]['valor'] = 0;
	$set_valores[2][1]['texto'] = "1";
	$set_valores[2][1]['valor'] = 1;
	$set_valores[2][2]['texto'] = "2";
	$set_valores[2][2]['valor'] = 2;
	$set_valores[2][3]['texto'] = "3";
	$set_valores[2][3]['valor'] = 3;
	$set_valores[2][4]['texto'] = "4";
	$set_valores[2][4]['valor'] = 4;
	$set_valores[2][5]['texto'] = "5";
	$set_valores[2][5]['valor'] = 5;
	$set_valores[2][6]['texto'] = "6";
	$set_valores[2][6]['valor'] = 6;
	$set_valores[2][7]['texto'] = "7";
	$set_valores[2][7]['valor'] = 7;
	$set_valores[2][8]['texto'] = "8";
	$set_valores[2][8]['valor'] = 8;
	$set_valores[2][9]['texto'] = "9";
	$set_valores[2][9]['valor'] = 9;
	$set_valores[2][10]['texto'] = "10";
	$set_valores[2][10]['valor'] = 10;
	// Establece las secciones de reactivos
	$secciones[1][0]['numeracion'] = "A"; // Establece la numeración para esta sección, dejar en blanco para no numerar.
	$secciones[1][0]['texto'] = "Deporte y Cultura: Sergio Chimal Méndez";
	$secciones[1][0]['limitada'] = ""; // Una palabra de una carrera limita a que solo esa carrera pueda acceder, si son varias separar por espacios. Dejar cadena vacía para que accedan todas.
	$secciones[1][1]['inicia'] = 1; // Número de reactivo con el que inicia la subsección
	$secciones[1][1]['termina'] = 2; // Número de reactivo con el que termina la subsección
	$secciones[1][1]['tipo'] = "CERRADA"; // Los valores posibles son "CERRADA", "MULTIPLE" o "ABIERTA"
	$secciones[1][1]['set_valores'] = 2; // En abierta poner 0
	$secciones[1][1]['cero'] = "NA"; // Si el valor de cero se tomará para no aplica poner "NA", para insuficiente "INS", si no hay valor cero poner ""
	$secciones[1][1]['comentario'] = false; // Indica si después del reactivo debe de haber un espacio para el comentario. Valores true o false.
	$secciones[1][1]['limitada'] = "";
	$secciones[2][0]['numeracion'] = "B";
	$secciones[2][0]['texto'] = "Orientación Educativa: Ulises Alejandro Sánchez Origel";
	$secciones[2][0]['limitada'] = "";
	$secciones[2][1]['inicia'] = 3;
	$secciones[2][1]['termina'] = 4;
	$secciones[2][1]['tipo'] = "CERRADA";
	$secciones[2][1]['set_valores'] = 2;
	$secciones[2][1]['cero'] = "NA";
	$secciones[2][1]['comentario'] = false;
	$secciones[2][1]['limitada'] = "";
	$secciones[3][0]['numeracion'] = "C";
	$secciones[3][0]['texto'] = "Servicio Social y Comunitario: Rocío del Carmen Medina Ramírez";
	$secciones[3][0]['limitada'] = "";
	$secciones[3][1]['inicia'] = 5;
	$secciones[3][1]['termina'] = 7;
	$secciones[3][1]['tipo'] = "CERRADA";
	$secciones[3][1]['set_valores'] = 2;
	$secciones[3][1]['cero'] = "NA";
	$secciones[3][1]['comentario'] = false;
	$secciones[3][1]['limitada'] = "";
	$secciones[4][0]['numeracion'] = "D";
	$secciones[4][0]['texto'] = "Servicio Médico: Estela Rodríguez Ramos";
	$secciones[4][0]['limitada'] = "";
	$secciones[4][1]['inicia'] = 8;
	$secciones[4][1]['termina'] = 10;
	$secciones[4][1]['tipo'] = "CERRADA";
	$secciones[4][1]['set_valores'] = 2;
	$secciones[4][1]['cero'] = "NA";
	$secciones[4][1]['comentario'] = false;
	$secciones[4][1]['limitada'] = "";
	$secciones[5][0]['numeracion'] = "E";
	$secciones[5][0]['texto'] = "Pastoral: Claudia Patricia Aguirre Macossay";
	$secciones[5][0]['limitada'] = "";
	$secciones[5][1]['inicia'] = 11;
	$secciones[5][1]['termina'] = 12;
	$secciones[5][1]['tipo'] = "CERRADA";
	$secciones[5][1]['set_valores'] = 2;
	$secciones[5][1]['cero'] = "NA";
	$secciones[5][1]['comentario'] = false;
	$secciones[5][1]['limitada'] = "";
	$secciones[6][0]['numeracion'] = "F";
	$secciones[6][0]['texto'] = "Jefatura de Formación Integral: Miguel Ángel Ramírez Cárdenas";
	$secciones[6][0]['limitada'] = "";
	$secciones[6][1]['inicia'] = 13;
	$secciones[6][1]['termina'] = 15;
	$secciones[6][1]['tipo'] = "CERRADA";
	$secciones[6][1]['set_valores'] = 2;
	$secciones[6][1]['cero'] = "NA";
	$secciones[6][1]['comentario'] = false;
	$secciones[6][1]['limitada'] = "";
	$secciones[7][0]['numeracion'] = "G";
	$secciones[7][0]['texto'] = "Escribe, si así lo deseas, algún comentario adicional respecto al tema...";
	$secciones[7][0]['limitada'] = "";
	$secciones[7][1]['inicia'] = 16;
	$secciones[7][1]['termina'] = 21;
	$secciones[7][1]['tipo'] = "ABIERTA";
	$secciones[7][1]['set_valores'] = 0;
	$secciones[7][1]['cero'] = "";
	$secciones[7][1]['comentario'] = false;
	$secciones[7][1]['limitada'] = "";
	// Establece el total de secciones y subsecciones así como de reactivos
	$total_secciones = 7;
	$total_subsecciones[1] = 1;
	$total_subsecciones[2] = 1;
	$total_subsecciones[3] = 1;
	$total_subsecciones[4] = 1;
	$total_subsecciones[5] = 1;
	$total_subsecciones[6] = 1;
	$total_subsecciones[7] = 1;
	$total_reactivos = 21;
	// Establece el número de respuestas posibles por renglón
	$valores_por_renglon = 11;
	// Establece el texto previo a los reactivos
	$previo['numeracion'] = "";
	$previo['encabezado'] = "Indicaciones";
	$previo['cuerpo'][] = "Califica cada una de las siguientes afirmaciones que corresponden a la Formación Integral, siendo 1 la calificación mínima y 10 la máxima.";
	// Establece el texto de los reactivos
	$texto_reactivo[1] = "El trato de la persona encargada fue amable y cordial";
	$texto_reactivo[2] = "El encargado de Deporte y Cultura motivó la participación en las actividades y eventos deportivos y culturales";
	$texto_reactivo[3] = "El trato de la persona encargada fue amable y cordial";
	$texto_reactivo[4] = "La atención recibida del responsable fue favorable para el proceso de resolución a tu necesidad inicial";
	$texto_reactivo[5] = "El trato de la persona encargada fue amable y cordial";
	$texto_reactivo[6] = "El encargado de servicio social da seguimiento a tu solicitud de atención";
	$texto_reactivo[7] = "El encargado de servicio social te ofrece diversas propuestas de servicio comunitario y social";
	$texto_reactivo[8] = "El trato de la persona encargada fue amable y cordial";
	$texto_reactivo[9] = "Los horarios de atención te permiten el uso del servicio médico";
	$texto_reactivo[10] = "La atención médica fue adecuada a tus necesidades";
	$texto_reactivo[11] = "El trato de la persona encargada fue amable y cordial";
	$texto_reactivo[12] = "La atención fue adecuada a tus necesidades";
	$texto_reactivo[13] = "El trato de la persona encargada fue amable y cordial";
	$texto_reactivo[14] = "La persona encargada guió y apoyó el proceso para resolver tus dudas o problemas";
	$texto_reactivo[15] = "En caso de ser becado por la Universidad se te informa sobre las opciones y formas de cumplir el servicio becario";
	$texto_reactivo[16] = "Deporte y Cultura";
	$texto_reactivo[17] = "Orientación Educativa";
	$texto_reactivo[18] = "Servicio Social y Comunitario";
	$texto_reactivo[19] = "Servicio Médico";
	$texto_reactivo[20] = "Pastoral";
	$texto_reactivo[21] = "Jefatura de Formación Integral";
	// Define el texto del encabezado de la evaluación
	$encabezado[1] = "Formación Integral";
	$encabezado[2] = "FIDCO";
	// Define la secuencia de campos a registrar en la base de datos (solo 3)
	$secuencia_sql[1] = "carrera, grado, sexo, situacion"; // Campos de la tabla adicionales a las meras respuestas
	$secuencia_sql[2] =  $_SESSION['zez_a_carrera'] . "', '" . $_SESSION['zez_a_grado'] . "', '" . $_SESSION['zez_a_sexo'] . "', '" . $_SESSION['zez_a_situacion'];
?>