<?php
	// Establece el tamaño de los distitntos sets de valores que se utilizarán, siempre el set 0 será de valor 1 porque es para las respuestas abiertas
	$tamano_set_valores[0] = 1;
	$tamano_set_valores[1] = 2;
	$tamano_set_valores[2] = 5;
	// Establece el set de valores para las respuestas cerradas y las de opción múltiple
	$set_valores[1][1]['texto'] = "Sí";
	$set_valores[1][1]['valor'] = 10;
	$set_valores[1][2]['texto'] = "No";
	$set_valores[1][2]['valor'] = 0;
	$set_valores[2][1]['texto'] = "1";
	$set_valores[2][1]['valor'] = 1;
	$set_valores[2][2]['texto'] = "2";
	$set_valores[2][2]['valor'] = 2;
	$set_valores[2][3]['texto'] = "3";
	$set_valores[2][3]['valor'] = 3;
	$set_valores[2][4]['texto'] = "4";
	$set_valores[2][4]['valor'] = 4;
	$set_valores[2][5]['texto'] = "5";
	$set_valores[2][5]['valor'] = 5;
	$set_valores[2][6]['texto'] = "6";
	$set_valores[2][6]['valor'] = 6;
	$set_valores[2][7]['texto'] = "7";
	$set_valores[2][7]['valor'] = 7;
	$set_valores[2][8]['texto'] = "8";
	$set_valores[2][8]['valor'] = 8;
	$set_valores[2][9]['texto'] = "9";
	$set_valores[2][9]['valor'] = 9;
	$set_valores[2][10]['texto'] = "10";
	$set_valores[2][10]['valor'] = 10;
	// Establece el multiplicador para obtener calificaciones base 100
	$multiplicador = 1; // 100 entre el máximo valor del set de valores
	// Establece las ponderaciones
	$ponderaciones['alumnos'] = 0.5;
	$ponderaciones['coordinadores'] = 0.4;
	$ponderaciones['autoevaluacion'] = 0.1;
	// Establece las secciones de reactivos
	$secciones[1][0]['numeracion'] = ""; // Establece la numeración para esta sección, dejar en blanco para no numerar.
	$secciones[1][0]['texto'] = "Reporte";
	$secciones[1][0]['limitada'] = ""; // Una palabra de una carrera limita a que solo esa carrera pueda acceder, si son varias separar por espacios. Dejar cadena vacía para que accedan todas.
	$secciones[1][1]['inicia'] = 1; // Número de reactivo con el que inicia la subsección
	$secciones[1][1]['termina'] = 6; // Número de reactivo con el que termina la subsección
	$secciones[1][1]['tipo'] = "CERRADA"; // Los valores posibles son "CERRADA", "MULTIPLE" o "ABIERTA"
	$secciones[1][1]['set_valores'] = 2; // En abierta poner 0
	$secciones[1][1]['cero'] = ""; // Si el valor de cero se tomará para no aplica poner "NA", para insuficiente "INS", si no hay valor cero poner ""
	$secciones[1][1]['comentario'] = false; // Indica si después del reactivo debe de haber un espacio para el comentario. Valores true o false.
	$secciones[1][1]['limitada'] = ""; // Una palabra de una carrera limita a que solo esa carrera pueda acceder, si son varias separar por espacios. Dejar cadena vacía para que accedan todas.
	$secciones[1][1]['retroalimentacion'] = "";
	$secciones[1][2]['inicia'] = 7;
	$secciones[1][2]['termina'] = 7;
	$secciones[1][2]['tipo'] = "CERRADA";
	$secciones[1][2]['set_valores'] = 1;
	$secciones[1][2]['cero'] = "";
	$secciones[1][2]['comentario'] = false;
	$secciones[1][2]['limitada'] = "";
	$secciones[1][3]['inicia'] = 8;
	$secciones[1][3]['termina'] = 23;
	$secciones[1][3]['tipo'] = "CERRADA";
	$secciones[1][3]['set_valores'] = 2;
	$secciones[1][3]['cero'] = "";
	$secciones[1][3]['comentario'] = false;
	$secciones[1][3]['limitada'] = "";
	$secciones[1][4]['inicia'] = 24;
	$secciones[1][4]['termina'] = 24;
	$secciones[1][4]['tipo'] = "ABIERTA";
	$secciones[1][4]['set_valores'] = 0;
	$secciones[1][4]['cero'] = "";
	$secciones[1][4]['comentario'] = false;
	$secciones[1][4]['limitada'] = "";
	// Establece el total de secciones y subsecciones así como de reactivos
	$total_secciones = 1;
	$total_subsecciones[1] = 4;
	$total_reactivos = 24;
	// Establece el número de respuestas posibles por renglón
	$valores_por_renglon = 5;
	// Establece el texto previo a los reactivos
	$previo['numeracion'] = "";
	$previo['encabezado'] = "";
	$previo['cuerpo'][] = "";
	// Establece el texto de los reactivos
	$reactivo[1]['competencia'] = "COMPETENCIAS TECNOLÓGICAS";
	$reactivo[1]['texto'] = "Habilita las actividades y productos de aprendizaje del curso en la plataforma digital establecida institucionalmente.";
	$reactivo[1]['alumnos'] = 1;
	$reactivo[1]['coordinadores'] = 1;
	$reactivo[1]['autoevaluacion'] = 1;
	$reactivo[2]['competencia'] = "COMPETENCIAS TECNOLÓGICAS";
	$reactivo[2]['texto'] = "Muestra dominio en el uso de plataformas digitales y recursos tecnológicos diversos para el desarrollo del curso.";
	$reactivo[2]['alumnos'] = 2;
	$reactivo[2]['coordinadores'] = 2;
	$reactivo[2]['autoevaluacion'] = 2;
	$reactivo[3]['competencia'] = "COMPETENCIAS TECNOLÓGICAS";
	$reactivo[3]['texto'] = "Promueve en los estudiantes el uso de e-libro, web y/o bases de datos para la búsqueda, localización y uso eficaz de la información.";
	$reactivo[3]['alumnos'] = 3;
	$reactivo[3]['coordinadores'] = 3;
	$reactivo[3]['autoevaluacion'] = 3;
	$reactivo[4]['competencia'] = "COMPETENCIAS COMUNICATIVAS";
	$reactivo[4]['texto'] = "Utiliza herramientas digitales para facilitar la comunicación académica e interpersonal con los estudiantes.";
	$reactivo[4]['alumnos'] = 4;
	$reactivo[4]['coordinadores'] = 4;
	$reactivo[4]['autoevaluacion'] = 4;
	$reactivo[5]['competencia'] = "COMPETENCIAS COMUNICATIVAS";
	$reactivo[5]['texto'] = "Utiliza un lenguaje claro y accesible que favorece el intercambio y el diálogo académico.";
	$reactivo[5]['alumnos'] = 5;
	$reactivo[5]['coordinadores'] = 5;
	$reactivo[5]['autoevaluacion'] = 5;
	$reactivo[6]['competencia'] = "COMPETENCIAS COGNITIVAS";
	$reactivo[6]['texto'] = "Demuestra conocimiento y dominio de su área profesional.";
	$reactivo[6]['alumnos'] = 6;
	$reactivo[6]['coordinadores'] = 6;
	$reactivo[6]['autoevaluacion'] = 6;
	$reactivo[7]['competencia'] = "COMPETENCIAS DE PLANEACIÓN";
	$reactivo[7]['texto'] = "Entregó en tiempo y forma el instrumento de diseño para el aprendizaje de competencias IPAC (secuencias de aprendizaje).";
	$reactivo[7]['alumnos'] = 0;
	$reactivo[7]['coordinadores'] = 7;
	$reactivo[7]['autoevaluacion'] = 0;
	$reactivo[8]['competencia'] = "COMPETENCIAS DE PLANEACIÓN";
	$reactivo[8]['texto'] = "Señala los aprendizajes esperados del curso que aportan a la formación profesional de los estudiantes.";
	$reactivo[8]['alumnos'] = 7;
	$reactivo[8]['coordinadores'] = 8;
	$reactivo[8]['autoevaluacion'] = 7;
	$reactivo[9]['competencia'] = "COMPETENCIAS DE PLANEACIÓN";
	$reactivo[9]['texto'] = "Especifica los tiempos y requisitos de entrega de las actividades de aprendizaje del curso.";
	$reactivo[9]['alumnos'] = 8;
	$reactivo[9]['coordinadores'] = 9;
	$reactivo[9]['autoevaluacion'] = 8;
	$reactivo[10]['competencia'] = "COMPETENCIAS DE PLANEACIÓN";
	$reactivo[10]['texto'] = "Cumple con los tiempos y actividades de aprendizaje programados para el logro de la competencia.";
	$reactivo[10]['alumnos'] = 9;
	$reactivo[10]['coordinadores'] = 10;
	$reactivo[10]['autoevaluacion'] = 9;
	$reactivo[11]['competencia'] = "COMPETENCIAS DIDÁCTICAS";
	$reactivo[11]['texto'] = "Utiliza diversos recursos y materiales que facilitan el aprendizaje significativo.";
	$reactivo[11]['alumnos'] = 10;
	$reactivo[11]['coordinadores'] = 11;
	$reactivo[11]['autoevaluacion'] = 10;
	$reactivo[12]['competencia'] = "COMPETENCIAS DIDÁCTICAS";
	$reactivo[12]['texto'] = "Implementa actividades de aprendizaje que relacionan la teoría con la práctica.";
	$reactivo[12]['alumnos'] = 11;
	$reactivo[12]['coordinadores'] = 12;
	$reactivo[12]['autoevaluacion'] = 11;
	$reactivo[13]['competencia'] = "COMPETENCIAS DIDÁCTICAS";
	$reactivo[13]['texto'] = "Emplea actividades de aprendizaje en situaciones reales del contexto profesional para el desarrollo de la competencia.";
	$reactivo[13]['alumnos'] = 12;
	$reactivo[13]['coordinadores'] = 13;
	$reactivo[13]['autoevaluacion'] = 12;
	$reactivo[14]['competencia'] = "COMPETENCIAS DE EVALUACIÓN";
	$reactivo[14]['texto'] = "Utiliza diferentes estrategias de evaluación para conocer el avance del aprendizaje y de la adquisición de la competencia.";
	$reactivo[14]['alumnos'] = 13;
	$reactivo[14]['coordinadores'] = 14;
	$reactivo[14]['autoevaluacion'] = 13;
	$reactivo[15]['competencia'] = "COMPETENCIAS DE EVALUACIÓN";
	$reactivo[15]['texto'] = "Realiza retroalimentación de las actividades de aprendizaje señaladas en el curso.";
	$reactivo[15]['alumnos'] = 14;
	$reactivo[15]['coordinadores'] = 15;
	$reactivo[15]['autoevaluacion'] = 14;
	$reactivo[16]['competencia'] = "COMPETENCIAS DE EVALUACIÓN";
	$reactivo[16]['texto'] = "Respeta los criterios de evaluación y porcentaje de calificación de conformidad a lo especificado al inicio del curso.";
	$reactivo[16]['alumnos'] = 15;
	$reactivo[16]['coordinadores'] = 16;
	$reactivo[16]['autoevaluacion'] = 15;
	$reactivo[17]['competencia'] = "COMPETENCIAS DE MANEJO DEL AMBIENTE";
	$reactivo[17]['texto'] = "Favorece el establecimiento de relaciones interpersonales cercanas basadas en el respeto y la tolerancia.";
	$reactivo[17]['alumnos'] = 16;
	$reactivo[17]['coordinadores'] = 17;
	$reactivo[17]['autoevaluacion'] = 16;
	$reactivo[18]['competencia'] = "COMPETENCIAS DE MANEJO DEL AMBIENTE";
	$reactivo[18]['texto'] = "Crea un ambiente de confianza y apertura para externar y resolver las dudas e inquietudes académicas.";
	$reactivo[18]['alumnos'] = 17;
	$reactivo[18]['coordinadores'] = 18;
	$reactivo[18]['autoevaluacion'] = 17;
	$reactivo[19]['competencia'] = "COMPETENCIAS DE MANEJO DEL AMBIENTE";
	$reactivo[19]['texto'] = "Muestra empatía y comprensión con las necesidades y dificultades presentadas en el proceso de aprendizaje.";
	$reactivo[19]['alumnos'] = 18;
	$reactivo[19]['coordinadores'] = 19;
	$reactivo[19]['autoevaluacion'] = 18;
	$reactivo[20]['competencia'] = "COMPETENCIAS PEDAGÓGICAS";
	$reactivo[20]['texto'] = "Muestra apertura a la autocrítica y a la retroalimentación de su quehacer docente.";
	$reactivo[20]['alumnos'] = 0;
	$reactivo[20]['coordinadores'] = 20;
	$reactivo[20]['autoevaluacion'] = 19;
	$reactivo[21]['competencia'] = "COMPETENCIAS PEDAGÓGICAS";
	$reactivo[21]['texto'] = "Participa en cursos y programas de formación docente.";
	$reactivo[21]['alumnos'] = 0;
	$reactivo[21]['coordinadores'] = 21;
	$reactivo[21]['autoevaluacion'] = 20;
	$reactivo[22]['competencia'] = "COMPETENCIAS PEDAGÓGICAS";
	$reactivo[22]['texto'] = "Contribuye activamente en el trabajo colegiado realizado en las carreras de adscripción.";
	$reactivo[22]['alumnos'] = 0;
	$reactivo[22]['coordinadores'] = 22;
	$reactivo[22]['autoevaluacion'] = 0;
	$reactivo[23]['competencia'] = "COMPETENCIAS PEDAGÓGICAS";
	$reactivo[23]['texto'] = "Reflexiona de manera individual y/o colegiada sobre las dificultades y problemáticas presentadas en la docencia.";
	$reactivo[23]['alumnos'] = 0;
	$reactivo[23]['coordinadores'] = 23;
	$reactivo[23]['autoevaluacion'] = 21;
	$reactivo[24]['competencia'] = "COMENTARIOS GENERALES";
	$reactivo[24]['texto'] = "Comentarios y sugerencias orientadas a la mejora de su quehacer docente.";
	$reactivo[24]['alumnos'] = 19;
	$reactivo[24]['coordinadores'] = 24;
	$reactivo[24]['autoevaluacion'] = 22;
	/*if(!isset($reporte)){
		// Define el texto del encabezado de la evaluación
		$encabezado[1] = $parametros[2];
		$encabezado[2] = "PROFESOR" . $parametros[4];
		// Define la secuencia de campos a registrar en la base de datos (solo 3)
		$secuencia_sql[1] = "nombre, sexo"; // Campos de la tabla adicionales a las meras respuestas
		$secuencia_sql[2] =  $parametros[2] . "', '" . $parametros[3];
	}*/
?>